// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4B-7YU8gxbYqGTL8vFz7_Vh2CRcXSA50',
    appId: '1:918857911935:web:fc192463b69e8aff1eb94a',
    messagingSenderId: '918857911935',
    projectId: 'authentication-a5adc',
    authDomain: 'authentication-a5adc.firebaseapp.com',
    storageBucket: 'authentication-a5adc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZqkqXVWqKSlHHzA2FOKp_2ogAb-PVsuk',
    appId: '1:918857911935:android:52b59dc06193e6b51eb94a',
    messagingSenderId: '918857911935',
    projectId: 'authentication-a5adc',
    storageBucket: 'authentication-a5adc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0n-jndNsIm0g2CFg8j5RGzK3U1RRApdQ',
    appId: '1:918857911935:ios:f37a51645e81c5c81eb94a',
    messagingSenderId: '918857911935',
    projectId: 'authentication-a5adc',
    storageBucket: 'authentication-a5adc.firebasestorage.app',
    iosBundleId: 'com.soumyadev.iosApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0n-jndNsIm0g2CFg8j5RGzK3U1RRApdQ',
    appId: '1:918857911935:ios:9231b4612d7f143f1eb94a',
    messagingSenderId: '918857911935',
    projectId: 'authentication-a5adc',
    storageBucket: 'authentication-a5adc.firebasestorage.app',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4B-7YU8gxbYqGTL8vFz7_Vh2CRcXSA50',
    appId: '1:918857911935:web:c8b2f39a5a1aeee61eb94a',
    messagingSenderId: '918857911935',
    projectId: 'authentication-a5adc',
    authDomain: 'authentication-a5adc.firebaseapp.com',
    storageBucket: 'authentication-a5adc.firebasestorage.app',
  );

}